from typing import Any, Protocol
from datetime import date


class Ledger(Protocol):
    def accounts(self) -> list[dict]: ...
    def categories(self) -> list[dict]: ...
    def rates(self) -> dict: ...
    def get(self, transaction_id: str) -> dict | None: ...
    def search(self, start: int, end: int, keyword: str | None = None) -> list[dict]: ...
    def create(self, payload: dict) -> dict: ...
    def modify(self, payload: dict) -> dict: ...
    def settlement_payload(self, current: dict, amount: int) -> dict: ...


class Mail(Protocol):
    def folders(self) -> list[str]: ...
    def scan(
        self, folder: str, after_uid: int = 0, since: date | None = None, until: date | None = None
    ) -> tuple[str, list[int]]: ...
    def fetch(self, folder: str, uid: int) -> bytes: ...


class Classifier(Protocol):
    def classify(self, row_id: str, merchant: str, categories: list[dict]) -> dict: ...


class Store(Protocol):
    def transaction(self) -> Any: ...
    def execute(self, sql: str, params: tuple = ()) -> Any: ...
    def one(self, sql: str, params: tuple = ()) -> dict | None: ...
    def all(self, sql: str, params: tuple = ()) -> list[dict]: ...
    def audit(self, event: str, entity_id: str, data: dict) -> None: ...
    def issue(self, code: str, entity_id: str, data: dict) -> None: ...
